---
apiVersion: v1
kind: Secret
metadata:
  namespace: datakitchen
  name: obs-poller-secret
type: Opaque
stringData:
  EVENTS_API_HOST: ''
  EVENTS_API_KEY: ''
  EVENT_HUB_CONN_STR: ''
  EVENT_HUB_NAME: ''
  AZURE_STORAGE_CONN_STR: ''
  BLOB_CONTAINER_NAME: ''
  EXTERNAL_PLUGINS_PATH: '/plugins'
  ENABLED_PLUGINS: ''
  PUBLISH_EVENTS: 'True'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs-poller-agent
  namespace: datakitchen
  labels:
    app: obs-poller-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obs-poller-agent
  template:
    metadata:
      labels:
        app: obs-poller-agent
    spec:
      containers:
      - name: obs-poller-agent
        image: dk-poller-obs-agent:latest
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: obs-docker-creds
